### ISSUE TITLE
URLs for Better call Dev not working

### ISSUE THREAD

**Issue by ktorn** [completium/completium-landing#2]
On the Try Archetype gitpod tutorial, the URLs for BCD are not appearing when running `show contract`, possibly because the tutorial is running on a mockup network.

Is there a way to switch the tutorial to a testnet?

```
$ completium-cli show contract 1-hello

Name     : 1-hello
Network  : mockup
Address  : KT1AB7MUUZM8RrWK96b7tnyWeBuB7hsCMJKU
Source   : /home/gitpod/.completium/sources/1-hello.arl
Language : archetype
Version  : 1.2.14
Url      : 
Path     : /home/gitpod/.completium/contracts/1-hello.tz
Storage  : ""
```

**Comment by rognierbenoit** [comment]
Hi @ktorn, yes you can use the following command to select (with up/down arrow then enter) a testnet
```sh
completium-cli switch endpoint
```

Typically you want `ithaca     https://ithacanet.ecadinfra.com`.

Indeed the BCD url is not showing with the `show contract` cmd (it is `https://better-call.dev/ithacanet/KT1.../operations` when on testnet)
